
### Obtener todas las categorías
GET http://localhost:8000/api/categories
Accept: application/json

### Crear una categoría
POST http://localhost:8000/api/categories
Content-Type: application/json
Accept: application/json

{
    "name": "Estudio",
    "color": "#1646a7ff"
}

### Obtener una categoría
GET http://localhost:8000/api/categories/2
Accept: application/json

### Actualizar una categoría
PUT http://localhost:8000/api/categories/4
Content-Type: application/json
Accept: application/json

{
    "name": "Programacion",
    "color": "#ff0000"
}

### Eliminar una categoría
DELETE http://localhost:8000/api/categories/4
Accept: application/json


///peticones para Tag 

### Obtener todas las etiquetas
GET http://localhost:8000/api/tags
Accept: application/json

### Crear una etiqueta
POST http://localhost:8000/api/tags
Content-Type: application/json
Accept: application/json

{
    "name": "Muy Importante",
    "color": "#ff0000"
}

### Obtener una etiqueta
GET http://localhost:8000/api/tags/1
Accept: application/json

### Actualizar una etiqueta
PUT http://localhost:8000/api/tags/3
Content-Type: application/json
Accept: application/json

{
    "name": "Mediobueno",
    "color": "#ff0000"
}

### Eliminar una etiqueta
DELETE http://localhost:8000/api/tags/1
Accept: application/json

/// provando las subtareas 

### Obtener todas las subtareas de una Tarea
GET http://localhost:8000/api/tasks/2/subtasks
Accept: application/json

### Crear una subtarea
POST http://localhost:8000/api/tasks/2/subtasks
Content-Type: application/json
Accept: application/json

{
    "title": "Comprar leche",
    "is_completed": false
}






/// retorna las tareas
### Retorna las tareas con sus relaciones
GET http://localhost:8000/api/tasks
Accept: application/json


### Crear tareas
POST http://localhost:8000/api/tasks
Content-Type: application/json
Accept: application/json

{
    "user_id": 1,
    "category_id": 1,
    "title": "Comprar pan",
    "description": "Comprar pan para el desayuno",
    "status": "pending",
    "priority": "high",
    "due_date": "2025-12-31",
    "is_completed": false
}


### Ver tareas
GET http://localhost:8000/api/tasks/1
Accept: application/json

### Actualizar tareas
PUT http://localhost:8000/api/tasks/1
Content-Type: application/json
Accept: application/json

{
     "status": "completed",
    "is_completed": true
}

### Eliminar tareas
DELETE http://localhost:8000/api/tasks/1
Accept: application/json
